export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16 space-y-10">

        <div className="space-y-2">
          <h1 className="text-4xl font-bold">Terms of Service</h1>
          <p className="text-muted-foreground text-sm">Last updated: May 20, 2025</p>
        </div>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
          <p className="leading-relaxed text-muted-foreground">
            By accessing or using LiteralLiterature ("the Service"), you agree to be bound by
            these Terms of Service. If you do not agree to all of these terms, do not use the
            Service. These terms apply to all visitors, users, and others who access or use the
            Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">2. Description of Service</h2>
          <p className="leading-relaxed text-muted-foreground">
            LiteralLiterature is an AI-powered tool that allows users to upload PDF documents
            and receive a series of AI-generated illustrations based on the text content of
            those documents. The Service uses large language models to interpret page text and
            image generation models to produce visual artwork.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">3. Eligibility</h2>
          <p className="leading-relaxed text-muted-foreground">
            You must be at least 13 years of age to use this Service. If you are under 18, you
            represent that you have your parent or guardian's permission to use the Service and
            that they have read and agreed to these Terms on your behalf.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">4. Your Content and Copyright Responsibility</h2>
          <p className="leading-relaxed text-muted-foreground">
            You are solely responsible for any PDF you upload. By uploading a document, you
            represent and warrant that:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground pl-4">
            <li>You own the document, or have the explicit legal right to use it for this purpose.</li>
            <li>Uploading and processing the document does not violate any copyright, trademark, trade secret, privacy, or other intellectual property right of any third party.</li>
            <li>The document does not contain content that is unlawful, defamatory, obscene, pornographic, or otherwise objectionable.</li>
          </ul>
          <p className="leading-relaxed text-muted-foreground">
            LiteralLiterature does not pre-screen uploaded content and is not responsible for
            copyright infringement caused by user uploads. We respond to valid DMCA takedown
            notices — see our Copyright Policy for details.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">5. AI-Generated Content</h2>
          <p className="leading-relaxed text-muted-foreground">
            All illustrations produced by this Service are generated by artificial intelligence.
            You acknowledge that:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground pl-4">
            <li>AI-generated images may be inaccurate, inconsistent, or unexpected in appearance.</li>
            <li>The copyright status of AI-generated images varies by jurisdiction and is subject to evolving law. LiteralLiterature makes no warranty that generated images are free of third-party intellectual property claims.</li>
            <li>You use AI-generated images at your own risk. We recommend seeking legal advice before using generated images for commercial purposes.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">6. Prohibited Uses</h2>
          <p className="leading-relaxed text-muted-foreground">
            You may not use the Service to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground pl-4">
            <li>Upload content that sexualizes minors in any way.</li>
            <li>Generate content that constitutes hate speech, incites violence, or targets individuals based on race, ethnicity, religion, gender, sexual orientation, or disability.</li>
            <li>Upload confidential, classified, or proprietary documents belonging to others without authorization.</li>
            <li>Attempt to reverse-engineer, exploit, or interfere with the Service's infrastructure.</li>
            <li>Use the Service for any unlawful purpose or in violation of any applicable regulations.</li>
            <li>Resell or redistribute access to the Service without written permission.</li>
          </ul>
          <p className="leading-relaxed text-muted-foreground">
            Violation of these prohibitions may result in immediate termination of your account
            and may be reported to relevant authorities where required by law.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">7. Payments and Pricing</h2>
          <p className="leading-relaxed text-muted-foreground">
            Pricing is calculated based on the number of pages processed. The price shown before
            processing begins is an estimate and is subject to the pricing schedule in effect at
            the time of your upload. All fees are non-refundable except where required by law.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">8. Data Storage and Retention</h2>
          <p className="leading-relaxed text-muted-foreground">
            Your uploaded PDFs and generated images are stored on secure cloud infrastructure.
            We retain your data for as long as your account is active or as needed to provide
            the Service. You may request deletion of your data at any time by contacting us.
            See our Privacy Policy for full details.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">9. Disclaimer of Warranties</h2>
          <p className="leading-relaxed text-muted-foreground">
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND,
            EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT
            THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED CONTENT WILL
            MEET YOUR EXPECTATIONS.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">10. Limitation of Liability</h2>
          <p className="leading-relaxed text-muted-foreground">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LITERALLITERATURE SHALL NOT BE
            LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
            INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH
            YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
            DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING UNDER THESE TERMS SHALL
            NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE MONTHS PRECEDING THE CLAIM.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">11. Termination</h2>
          <p className="leading-relaxed text-muted-foreground">
            We reserve the right to suspend or terminate your access to the Service at any
            time, with or without notice, for conduct that we believe violates these Terms or
            is harmful to other users, us, or third parties. Upon termination, your right to
            use the Service ceases immediately.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">12. Changes to These Terms</h2>
          <p className="leading-relaxed text-muted-foreground">
            We may update these Terms from time to time. When we do, we will update the "Last
            updated" date above. Your continued use of the Service after changes are posted
            constitutes your acceptance of the revised Terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">13. Governing Law</h2>
          <p className="leading-relaxed text-muted-foreground">
            These Terms are governed by and construed in accordance with applicable law. Any
            disputes arising under these Terms shall be resolved through binding arbitration or
            in the courts of competent jurisdiction where the Service operator is located.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">14. Contact</h2>
          <p className="leading-relaxed text-muted-foreground">
            If you have questions about these Terms, please contact us through the support
            channel provided in the application.
          </p>
        </section>

        <div className="pt-8 border-t border-border text-sm text-muted-foreground">
          <a href="/" className="hover:underline">← Back to LiteralLiterature</a>
        </div>
      </div>
    </div>
  );
}
